config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(strong_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def strong_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(strong_params)
    @review.restaurant_id = @restaurant.id
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
    end
  end

  private

  def strong_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

      <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1> Restaurants </h1>
  <ul>
    <% @restaurants.each do |restaurant| %>
    <li> <%= link_to restaurant.name, restaurant_path(restaurant) %> <%= restaurant.address %></li>
    <% end %>
  </ul>

  <%= link_to 'Add your favorite restaurant', new_restaurant_path, class: 'btn btn-success'%>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Add your restaurant info 🍔</h1>
  <%= simple_form_for(@restaurant) do |f|%>
    <%= f.input :name%>
    <%= f.input :category%>
    <%= f.input :address%>
    <%= f.input :phone_number%>
    <%= f.submit "Add restaurant", class: "btn btn-success"%>
  <% end %>
  <%= link_to 'Get back', restaurants_path, class: 'btn'%>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1> <%= @restaurant.name %> </h1>
  <div class="info flex">
    <p>Cuisine: <%= @restaurant.category %> </p>
    <p>Location: <%= @restaurant.address %> </p>
    <p>Contact: <%= @restaurant.phone_number || 'No contact info existing' %> </p>
  </div class="info flex">

  <div class="reviews-container">
    <% @restaurant.reviews.each do |review| %>
    <div class="review">
      <%= review.content %>
      <p> Rating: <%= review.rating %> </p>
    </div>
    <% end %>
  </div>

  <h4> Add a review for <%= @restaurant.name %> 📝 </h4>
  <%= simple_form_for([@restaurant, @review]) do |f|%>
    <%= f.input :content%>
    <%= f.input :rating%>
    <%= f.submit "Submit review", class: "btn btn-success" %>
  <% end %>

  <%= link_to 'Get back', restaurants_path, class: 'btn'%>
</div>